apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tfbridge.fullname" . }}
  labels:
    {{- include "tfbridge.labels" . | nindent 4 }}
data:
  tfbridge.yaml: |-
    server:
      port: {{.Values.httpPort}}
    management:
      server:
        port: {{.Values.mgmtPort}}
      endpoint:
        health:
          show-details: always
      endpoints:
        web:
          exposure:
            include: "*"
    bridge:
      {{- toYaml .Values.bridge | nindent 6}}
      mqtt:
        service: {{.Values.}}
    spring:
      {{- toYaml .Values.spring | nindent 6}}
