{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tfbridge.fullname" . }}
  labels:
    {{- include "tfbridge.labels" . | nindent 4 }}
{{- end -}}
