# Default values for tfbridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/koa1/tfbridge
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent
httpPort: 8080
mgmtPort: 9080
mqtt:
  service: mosquitto
spring: {}
bridge: {}
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
serviceAccount:
  create: true

nodeSelector: {}

tolerations: []

affinity: {}
