# Default values for tfbridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/koa1/tfbridge
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent
httpPort: 8080
mgmtPort: 9080
tfInstances:
  - 127.0.0.1
bricklets:
  BmS:
    name: Keller Licht 1
  Bom:
    name: Keller Licht 2
  BmN:
    name: Keller Licht 3
  BnF:
    name: Keller Licht 4
  H7C:
    name: Test LCD
  t2Y:
    name: Test Temp
  wre:
    name: Test Motion detector v1
  HA5:
    name: Keller Serverraum
  EJy:
    name: DMX Bricklet test
    dmxChannels:
      - Stripe 1 Warm
      - Stripe 1 Cold

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
serviceAccount:
  create: true

nodeSelector: {}

tolerations: []

affinity: {}
